name: DoubleTimeCommands
main: xyz.acrylicstyle.doubletimecommands.DoubleTimeCommands
version: 0.0.1
depend: [TomeitoLib]

commands:
  setspawnonjoin:
    description: "Sets if spawn on join, true or false."
    usage: /<command> [true/false]
    permission: doubletimecommands.commands.setspawnonjoin
  setgamemodeonjoin:
    description: "Set if set gamemode on join, survival, creative, adventure or spectator."
    usage: /<command> <adventure/creative/survival/spectator/null>
    permission: doubletimecommands.commands.setgamemodeonjoin
  nick:
    description: "Sets nickname."
    aliases: ["nickname","setnick","setnickname"]
    usage: /<command> <new nick> [player]
    permission: doubletimecommands.commands.nick
  prefix:
    description: "Sets prefix."
    aliases: ["setprefix"]
    usage: /<command> <new prefix> [player]
    permission: doubletimecommands.commands.prefix
  resetnick:
    description: "Reset nickname."
    aliases: ["deletenick", "unnick"]
    usage: /<command> [player]
    permission: doubletimecommands.commands.unnick
  resetprefix:
    description: "Reset prefix."
    aliases: ["deleteprefix", "unprefix"]
    usage: /<command> [player]
    permission: doubletimecommands.commands.resetprefix
  maintenance:
    description: "Toggles maintenance mode"
    usage: /<command>
    permission: doubletimecommands.commands.maintenance
  kickall:
    description: "What a guy!"
    usage: /<command> [reason]
    permissions: doubletimecommands.commands.kickall
  refreshrank:
    description: "Refreshes your rank."
    usage: /<command>
  transfer:
    description: "Transfer player to the specific game."
    usage: /<command> <game>
  servers:
    description: "Shows server list"
    usage: /<command>
  spawn:
    description: "Teleports you to the world spawn point"
    usage: /<command>
    aliases:
      - "stuck"